Repository AstarVienna/ScopeSim_Templates, pull requests merged in 2024-11, with the labels that each got.

#106 Add docstring tests to CI
  .github/workflows/tests.yml
  poetry.lock
  pyproject.toml
Labels: tests, github_actions

#108 Fix and improve RTD page
  docs/conf.py
  docs/contributions.rst
  docs/generated/scopesim_templates.calibration.empty_sky.rst
  docs/generated/scopesim_templates.calibration.flat_field.rst
  docs/generated/scopesim_templates.calibration.lamp.rst
  docs/generated/scopesim_templates.extragalactic.elliptical.rst
  docs/generated/scopesim_templates.extragalactic.galaxy.rst
  docs/generated/scopesim_templates.extragalactic.galaxy3d.rst
  docs/generated/scopesim_templates.extragalactic.spiral_two_component.rst
  docs/generated/scopesim_templates.misc.point_source.rst
  docs/generated/scopesim_templates.misc.source_from_array.rst
  docs/generated/scopesim_templates.misc.source_from_cube.rst
  docs/generated/scopesim_templates.misc.source_from_file.rst
  docs/generated/scopesim_templates.misc.source_from_imagehdu.rst
  docs/generated/scopesim_templates.misc.source_from_imagehdu_with_flux.rst
  docs/generated/scopesim_templates.misc.uniform_source.rst
  docs/generated/scopesim_templates.stellar.cluster.rst
  docs/generated/scopesim_templates.stellar.star.rst
  docs/generated/scopesim_templates.stellar.star_field.rst
  docs/generated/scopesim_templates.stellar.star_grid.rst
  docs/generated/scopesim_templates.stellar.stars.rst
  docs/index.md
  docs/index.rst
  docs/modules.rst
  docs/notebooks/extragalactic.ipynb
  docs/notebooks/extragalactic.md
  docs/notebooks/starting.ipynb
  docs/notebooks/starting.md
  docs/notebooks/stellar.ipynb
  docs/notebooks/stellar.md
  docs/source_object.md
  docs/source_object.rst
  docs/starting.rst
  poetry.lock
  pyproject.toml
  scopesim_templates/calibration/calibration.py
  scopesim_templates/extragalactic/__init__.py
  scopesim_templates/misc/misc.py
  scopesim_templates/stellar/__init__.py
Labels: documentation, dependencies

#109 Remove patchy getattrs now that ScopeSim v0.9.0 is here
  scopesim_templates/tests/test_calibration/test_calibration.py
  scopesim_templates/tests/test_micado/test_cluster.py
  scopesim_templates/tests/test_micado/test_darkness.py
  scopesim_templates/tests/test_micado/test_flatlamp.py
  scopesim_templates/tests/test_micado/test_pinhole_mask.py
  scopesim_templates/tests/test_micado/test_spectral_calibrations.py
  scopesim_templates/tests/test_stellar/test_clusters.py
  scopesim_templates/tests/test_stellar/test_stars.py
  scopesim_templates/tests/test_utils/test_validate_content.py
Labels: tests

#111 Improve API ref on RTD
  docs/_templates/custom-class-template.rst
  docs/_templates/custom-module-template.rst
  docs/conf.py
  docs/index.md
  poetry.lock
  pyproject.toml
Labels: documentation

#113 Prepare for 0.6.1 release
  poetry.lock
  pyproject.toml
Labels: no release notes

#114 Add more module docstrings for API reference
  scopesim_templates/extragalactic/agns.py
  scopesim_templates/extragalactic/clusters.py
  scopesim_templates/extragalactic/exgal_models.py
  scopesim_templates/extragalactic/galaxies.py
  scopesim_templates/extragalactic/galaxy_utils.py
  scopesim_templates/extragalactic/quasars.py
  scopesim_templates/stellar/clusters.py
  scopesim_templates/stellar/imf.py
  scopesim_templates/stellar/stars.py
  scopesim_templates/stellar/stars_utils.py
Labels: documentation
