Repository AstarVienna/ScopeSim_Templates, pull requests merged in 2025-04, with the labels that each got.

#130 Add padding option to `import_line_spectrum()`
  scopesim_templates/micado/spectral_calibrations.py
  scopesim_templates/tests/test_micado/test_spectral_calibrations.py
Labels: enhancement

#136 Fix wrong specref in pinhole_mask
  scopesim_templates/micado/pinhole_masks.py
Labels: bugfix

#137 Make ScopeSim_Templates test work without internet with -m "not webtest"
  .github/workflows/tests.yml
  scopesim_templates/stellar/cluster_utils.py
  scopesim_templates/tests/test_calibration/test_calibration.py
  scopesim_templates/tests/test_extragalactic/test_galaxy.py
  scopesim_templates/tests/test_micado/test_cluster.py
  scopesim_templates/tests/test_micado/test_viking_fields.py
  scopesim_templates/tests/test_misc/test_misc.py
  scopesim_templates/tests/test_stellar/test_cluster_utils.py
  scopesim_templates/tests/test_stellar/test_clusters.py
  scopesim_templates/tests/test_stellar/test_star_utils.py
  scopesim_templates/tests/test_stellar/test_stars.py
  scopesim_templates/tests/test_utils/test_cleared_cache.py
  scopesim_templates/tests/test_utils/test_validate_content.py
Labels: refactor, tests
